import copy
import os

ddk_home = '/home/ubuntu/hiai-studio-rt/tools/che/ddk/ddk/'



inc_path = [
    ddk_home +'include/inc',
    ddk_home +'include/third_party/protobuf/include',
    ddk_home +'include/third_party/cereal/include',
    ddk_home +'include/libc_sec/include',
    '../../inc'
]


lib_path = [
    #ddk_home + '/lib/x86_64-linux-gnu' ,
   ddk_home + '/lib/aarch64-linux-gcc6.3' ,
]

libs = [
   'Dvpp_api' ,
   'Dvpp_jpeg_decoder',
   'Dvpp_jpeg_encoder',
   'Dvpp_vpc'
]
cxx_host = 'g++'
cxx_device = ddk_home+'toolchains/aarch64-linux-gcc6.3/bin/aarch64-linux-gnu-g++'

src = Glob('*.cpp') + Glob('../../src/util.cpp')
cpp_flags = ['-std=c++11', '-fPIC']
link_flags = ['-std=c++11', '-fPIC']

sharedlib  = SharedLibrary(
    target = 'libinferengine.so',
    source = src,
    CXX = cxx_device,
    CPPFLAGS = cpp_flags,
    LIBPATH =  lib_path,
    CPPPATH = inc_path,
    LIBS =  libs,
    LINKFLAGS = link_flags, 
)

#Install("./", sharedlib)

